---
- name: Build Podman Image duckhunt
  hosts: podman-master.local.dev
  tasks:
          - name: build podman duckhunt
            command: podman build -t stardew --file stardew-multiplayer-docker/docker/Dockerfile
