---
- name: Build Podman Image stardew
  hosts: podman-master.local.dev
  tasks:
          - name: build podman stardew
            command: podman build -t stardew --file stardew-multiplayer-docker/docker/Dockerfile
