---
- name: Build Podman Image duckhunt
  hosts: podman-master.local.dev
  tasks:
          - name: build podman duckhunt
            command: podman build -t duckhunt-js:v1 --file DuckHunt-JS-K8s/Dockerfile
