---
- name: Run Container Image duckhunt
  hosts: podman-master.local.dev
  tasks:
          - name: Run Container Image duckhunt v1
            command: podman run -d --name duckhunt -p 8081:80 duckhunt-js:v1
