---
- name: Check Disk Space Usage
  hosts: all
  tasks:
          - name: Disk usage from command module
            command: df -Th
            register: space
          - debug:
                  var: space.stdout_lines
